name: 'Composite Action 2'

description: 'Composite Action 2'

inputs:
  name:
    description: Username
    required: false
    default: ${{ github.actor }}
    
runs:
  using: "composite"
  steps:
    - name: Pegar resultado
      uses: ./composite-action-1/action.yml
      with:
        name: ${{ inputs.name }}
